### ISSUE TITLE
Syriaca bibls in corpus texts

### ISSUE THREAD

**Issue by nathangibson** [srophe/syriac-corpus#100]
@jedwardwalters How are you planning to mark the Syriaca.org bibl URIs of transcribed editions in corpus texts? E.g., http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/101/tei I see a biblStruct in the sourceDesc. Will an idno go into the first child of biblStruct here as we do in the Works Cited module? If you are able to do an example, this would help with https://github.com/srophe/srophe-eXist-app/issues/973. Thanks!

E.g.,
```
<sourceDesc>
                <biblStruct>
                    <analytic>
                        <editor>D. Alphonsi Mingana</editor>
                        <idno type="URI">http://syriaca.org/1765</idno>
                    </analytic>
                    <monogr>
                        <title level="a">Narsai Doctoris Syri Homiliae et Carmina</title>
                        <imprint>
                            <pubPlace>Mosul</pubPlace>
                            <publisher>Typis Fratrum Praedicatorum</publisher>
                            <date when="1905">1905</date>
                        </imprint>
                        <extent>2 Volumes</extent>
                        <biblScope type="vol">2</biblScope>
                        <biblScope type="pp">303-314</biblScope>
                    </monogr>
                </biblStruct>
            </sourceDesc>
```

**Comment by jedwardwalters** [comment]
@nathangibson 
Okay, I did a test here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/27.xml#L80

It validates, and if this is already what you do in the Works Cited thing, then I think this is a fine system to adopt. 

Look okay to you?

**Comment by nathangibson** [comment]
Yes, this looks great and matches the Works Cited module usage. Thanks!

**Comment by jedwardwalters** [comment]
Closing this because I think it's resolved.
