### ISSUE TITLE
Categories of entries

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#146]
Define categories of entries:
transcription
ecclectic edition
diplomatic edition

**Comment by jedwardwalters** [comment]
**Transcription**
The typed contents of an object--either a print edition or a manuscript.

1. Manuscript Transcription (MT): Text typed from a manuscript; may or may not include folio numbers.

2. Print Edition Transcription (PT): Text typed from a print edition; may or may not include para-textual components like page numbers, critical apparatus, headings, notes, etc.

**Edition**
A born-digital edition of a text, manuscript, or corpus.

1. Eclectic Edition (EE): An eclectic-style critical text (i.e. the text itself is the product of the editor, not a representation of any single version of the text) with notes, critical apparatus, etc.

2. Diplomatic Edition (DE): An edition of a text that is based on one primary manuscript; may or may not include critical apparatus (if there are other manuscript witnesses).

3. Manuscript Edition (ME): Beyond just transcription, this is a digital representation of an entire manuscript. [Is this a necessary category?]

**Comment by jedwardwalters** [comment]
@davidamichelson @dlschwartz  Have a look at the categories above--do these make sense? Any suggestions?

**Comment by davidamichelson** [comment]
This is a good start. Let's discuss in person.

**Comment by dlschwartz** [comment]
Agreed on both points Dave.

**Comment by jedwardwalters** [comment]
Resolved.
