### ISSUE TITLE
editionStmt

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#147]
@davidamichelson I've been thinking about the editionStmt thing we talked about, and I came up with an idea. Tell me what you think of this (this is for Aphrahat Dem 1):
`<editionStmt>
                <edition n="PT1">Transcription of print edition</edition>
                <respStmt>
                    <resp>Trascription</resp>
                    <name type="person" ref="http://syriaca.org/person.xml#dtaylor">David G.K. Taylor</name>
                </respStmt>
            </editionStmt>`

2 main things to note here:
1) "PT1" = "Print Transcription version 1"
If anyone comes through and fixes typos or generally edits it, we can upgrade it to PT2 and reflect that with a revision status.

2) Then we can use other abbreviations to distinguish the type of edition. For example:
MT = Manuscript transcription
DE = Diplomatic Edition
EE = Eclectic Edition

The final two could also be augmented as:
TDE = Transcribed Diplomatic Edition
DDE = Digital (i.e. born-digital) Diplomatic Edition

Maybe this is too complicated.

**Comment by davidamichelson** [comment]
Did you see the commits I sent with a sample?

**Comment by jedwardwalters** [comment]
Oh, no I hadn't seen that. I'll go check it out now.

**Comment by jedwardwalters** [comment]
Okay. Now I've seen it. 
That looks pretty similar to what I have in mind. Though I figured we may as well include the name of the transcriber in a respStmt.

I think your type="manuscript" is fine for the schema I have above, as long as we have a one-word representation of the different types of editions.

**Comment by jedwardwalters** [comment]
See here for an attempt at spelling out the different categories: https://github.com/srophe/syriac-corpus/issues/146

**Comment by davidamichelson** [comment]
Great, let's try to meet in person to discuss.

**Comment by jedwardwalters** [comment]
I'm available every day this week from 9 am-noon (eastern). Could also do afternoons, but need to work around kids' naps.

**Comment by jedwardwalters** [comment]
Oops. Didn't mean to close it.

**Comment by jedwardwalters** [comment]
Sounds good. I'm fairly wide open in the mornings to meet.

**Comment by jedwardwalters** [comment]
For discussion, here's a TEI header template from the Library of Digital Latin Texts:
```
<teiHeader>
    <fileDesc>
      <titleStmt>
        <title>TITLE</title>
        <author>ORIGINAL AUTHOR</author>
        <editor>EDITOR NAME</editor>
      </titleStmt>
      <editionStmt>
        <edition>First Edition</edition>
      </editionStmt>
      <publicationStmt>
        <publisher>Society for Classical Studies</publisher>
        <distributor>Digital Latin Library</distributor>
        <date>2016</date>
        <availability>
          <licence target="https://creativecommons.org/licenses/by/4.0/">Distributed under a
            Creative Commons Attribution 4.0 International License.</licence>
        </availability>
      </publicationStmt>
      <seriesStmt>
        <title level="s">Library of Digital Latin Texts</title>
        <biblScope unit="vol">1</biblScope>
      </seriesStmt>
      <sourceDesc>
        <p>Born digital.</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
```

**Comment by jedwardwalters** [comment]
I think we have wrapped this up elsewhere.
