### ISSUE TITLE
Numbers in Titles

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus#16]
@nathangibson @jedwardwalters in order for titles to appear in proper numeric order when alphabetized (such as here: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/browse.html?view=facets) we need all numbers in work titles to be wrapped in tei:num (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-num.html). Also in the case of roman numerals, it should also have the @value in arabic numerals. Perhaps as a rule though we should not use Roman numerals in our preferred titles.

Could you work together to make these changes to the titles?

Also beyond this we will need all titles for anything that is multi-part to use the @n attribute so they can be order correctly. This is more complex and needs discussion.

**Comment by jedwardwalters** [comment]
Okay, I'll work on the tei:num issue and wait on the @n until we discuss.

**Comment by nathangibson** [comment]
OK, @wsalesky here are some records for you to test https://github.com/srophe/syriac-corpus/commit/0fdc5e2ea6584016807f0ccf5ad34554ab4beac1. Please delete these when you are done. 

The sorting order of these should be:
Genesis
Exodus
Matthew
Mark

Thanks!

**Comment by wsalesky** [comment]
Interesting, looks like the current sorting works correctly. I think we will move ahead with it, and see if we need to make adjustments as the data gets more complicated.

**Comment by jedwardwalters** [comment]
I think we've got this worked out.
