### ISSUE TITLE
Citation for 1905 Bible Societies Edition

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus#161]
@jedwardwalters I updated the record for http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/100 with the biblStruct from http://wwwb.library.vanderbilt.edu/bibl/2491 

I think that all of the other biblical books need this same update as their current citation is not rendering right under "source"/

**Comment by jedwardwalters** [comment]
Got it. Will do.

**Comment by jedwardwalters** [comment]
Done.
