### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#200]
@wsalesky I was just looking for something in the corpus documentation, and that page is not showing anything on the production server. Any ideas?

https://syriaccorpus.org/documentation/index.html

**Comment by wsalesky** [comment]
Looks like it is not pointing to the wiki. I will troubleshoot...

**Comment by jedwardwalters** [comment]
I'm happy to fix it if you can point me in the right direction.

**Comment by wsalesky** [comment]
@jedwardwalters actually it is pointing to the wiki. https://github.com/srophe/syriac-corpus-app/blob/master/documentation/wiki.html#L16

curious. (by which i mean, annoying)

**Comment by wsalesky** [comment]
Fixed. Sorry about that.

**Comment by jedwardwalters** [comment]
Thank you!
