### ISSUE TITLE
Webhook fail

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#202]
@wsalesky Also, I just tried adding a new text, and the webhook failed. Not sure why exactly.

**Comment by wsalesky** [comment]
sent

**Comment by wsalesky** [comment]
@jedwardwalters can you point me to the file or commit that failed to upload?

**Comment by jedwardwalters** [comment]
Here's the commit:
https://github.com/srophe/syriac-corpus/commit/9d0ab8d14d7854ab675810340032336e857c5143

File is 387.xml

**Comment by wsalesky** [comment]
@jedwardwalters Thanks, I fixed it. There was a bug for loading new files. The script was using the wrong file format. https://syriaccorpus.org/387

**Comment by jedwardwalters** [comment]
Thanks. Do I still need to reset the permissions on git-sync?

**Comment by wsalesky** [comment]
Nope. Well, you do for Hugoye, if you deployed a new .xar file to get the
new issue up. I confused which app we were discussing.
The corpus should be fine.

**Comment by jedwardwalters** [comment]
Ah, okay. Got it. I did do that for Hugoye earlier this week, so that should be fine.
