### ISSUE TITLE
Dated texts-ready for testing

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#220]
@wsalesky Okay, I have a batch of texts edited and ready for testing. I added the date data in the profileDesc after the langUsage declaration (I checked with Dan and he agreed this was the most natural place for it in our data structure). So, it looks like this:
`<profileDesc>
            <langUsage>
                <language ident="syr">Unvocalized Syriac of any variety or period</language>
            </langUsage>
            <creation>
                <origDate type="translation" from="0350" to="0450">Late 4th/early 5th century CE
                <note>Translated from Greek into Syriac</note></origDate>
            </creation>
        </profileDesc>`

I used a type attribute to say whether it's a "translation" or "composition" because that may be something we want later. But for now we can just focus on the dates. As discussed previously, when there's a range, I used "from/to" attributes, and when there's a specific date, I used "when".

There are different texts with different dates and ranges in the test batch, so it should be a good sample to test. Let me know if you need anything else.

**Comment by jedwardwalters** [comment]
Oh, and it looks like the webhook failed. Should I manually upload them?

**Comment by wsalesky** [comment]
@jedwardwalters I will take care of it. I'm going to load them in my local instance first. Less chance of breaking the dev server. When I have something ready for you I will load them on the dev server with the new code. I can probably have it up on Monday, I have a kid at home today so coding is sporadic.

**Comment by jedwardwalters** [comment]
@wsalesky Monday (or even later next week) is fine!

**Comment by wsalesky** [comment]
@jedwardwalters ready for testing. 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html

Let me know if you want to add a date slider function to the facets on the search or browse results. That shouldn't take very long to add.

**Comment by wsalesky** [comment]
@jedwardwalters I added the slider, you can see it when you run a search, above the facets. We can put it anywhere you like, but at least you can test it and see if you like the function. We can remove it if you don't want it. Let me know if you find bugs or need tweaks.

**Comment by jedwardwalters** [comment]
This looks really great, @wsalesky. It seems to be working as expected, though it's a little hard to tell because it seems like the dev server doesn't have the search feature that ignores vowels. That's not a huge problem or anything...I just can't fully tell if it's returning all of the expected results.

I kind of like having the search box the way you have it now and then having the slider on the results page. I don't think we need the slider in both places. One thing I noticed: if you use the years without the initial 0 (so, range of 300-500 instead of 0300 to 0500), the search results still work, but the slider bar doesn't appear on the results page. For example, see [these results](http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%A2%DC%A6%DC%AB%DC%90&keywordProximity=&author=&title=&fq=&section=&corpus-uri=&syriaca-uri=&text-id=&startDate=300&endDate=500).

Again, it's hard to know for sure, but it seems like it's mostly functioning correctly. 

Just one small issue on display: the date boxes on the slider are covering up the "Date Range" title. Not a huge problem, but visually it doesn't look great. See screenshot below:
<img width="555" alt="Screen Shot 2019-04-29 at 2 43 58 PM" src="https://user-images.githubusercontent.com/11543800/56919003-7e18d380-6a8d-11e9-988b-d9fc82853f0c.png">

**Comment by wsalesky** [comment]
@jedwardwalters Okay, I think I have both issues fixed. Let me know what you think.

**Comment by jedwardwalters** [comment]
@wsalesky This is looking great. One more tiny thing (and this may be unavoidable, but I thought I'd check). When you use the slide bar, it automatically assigns a specific date (with month and day) to the year you've chosen. See picture below. Is it possible to make it only show the year?
<img width="598" alt="Screen Shot 2019-04-29 at 8 53 47 PM" src="https://user-images.githubusercontent.com/11543800/56935767-4c216480-6ac1-11e9-9adf-ae0e560db1c6.png">

**Comment by wsalesky** [comment]
@jedwardwalters done.

**Comment by jedwardwalters** [comment]
Thanks so much. I just noticed, though, that now when you do an initial search in a date range, the dates do not show up in that same spot, and they are also showing up highlighted as if they were the word being searched for. See [these results here ](http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%A1%DC%98%DC%AC%DC%90&keywordProximity=&author=&title=&fq=&section=&corpus-uri=&syriaca-uri=&text-id=&startDate=0300&endDate=0800)and screen shot:
![Screen Shot 2019-04-30 at 9 52 45 AM](https://user-images.githubusercontent.com/11543800/56966894-0cdd2d00-6b2e-11e9-8f4e-ad65a57e815d.png)

**Comment by wsalesky** [comment]
Fixed.

**Comment by jedwardwalters** [comment]
Thanks! I'm really happy with this. I'll run it by Dave and Dan and see if they have any thoughts. Hopefully very soon we'll be able to push this over to production. We can do sort of a soft launch of this until I get everything that's currently in the corpus dated, then do an official announcement.

**Comment by wsalesky** [comment]
@jedwardwalters I think this is a stale issue and am closing. If it still needs attention, please reopen.
