### ISSUE TITLE
Display for biblical texts

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#40]
@dlschwartz @davidamichelson @nathangibson 
Any thoughts on these two options for the display for a biblical text?

1) http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/100

2) http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/101

If I understood @wsalesky  correctly, we may be able to toggle between the line and paragraph display. But I thought I'd seek out opinions on which one should be the standard (and whether or not we think the toggle feature is worth it).

The second option (displaying the verse numbers within the paragraph element) definitely has some problems because of the right-to-left conversion. But aside from that problem, any preferences on display style?

**Comment by nathangibson** [comment]
I personally prefer the paragraph style, though I think a toggle option would be nice. 

BTW, the font size for the line style is pretty huge on my display (and the paragraph style is perhaps a bit small). Also, the TOC links in the left sidebar don't work for me for the line style (they do nothing when I click on them).

**Comment by nathangibson** [comment]
Where are the biblical texts coming from? I would like to cite the Syriac titles in NHSL. Thanks!

**Comment by jedwardwalters** [comment]
I just checked Carrie Schroeder's Coptic Scriptorium XML set up for Biblical texts, and it looks like they are doing individual xml files for each chapter. Then, they mark each verse with both a <div> (with n= verse number) and then <ab> within that <div>.

**Comment by jedwardwalters** [comment]
It's also perhaps worth noting that the very first example given on the <ab> element page is a biblical text!
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-ab.html

**Comment by jedwardwalters** [comment]
@dlschwartz @davidamichelson @nathangibson 
I adjusted one of the biblical texts with <ab> elements for testing display purposes. You can see the code here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/100.xml#L112

I didn't use paragraph elements because I noticed that most of the <ab> example texts they give don't use paragraphs within the div. I'm open to adding that, but unless we are breaking up individual paragraphs within chapters, I'm not sure that's actually necessary or preferable?

So perhaps for @wsalesky, in these cases the div would simply represent the "paragraph" display, and then we could have a display toggle for breaking it out verse by verse. 

Any thoughts from anyone?

**Comment by davidamichelson** [comment]
FYI @jedwardwalters we radically reconsidered the layout today to perhaps
use Divs differently, so we should confer before you do more encoding.

**Comment by jedwardwalters** [comment]
@davidamichelson Okay, got it.

Should I just wait until next Tuesday to get caught up? Or do you want to chat separately?

**Comment by davidamichelson** [comment]
May be best to wait until we can all discuss

**Comment by jedwardwalters** [comment]
Closing this and starting a new issue
