### ISSUE TITLE
Chron. Ed. numbering

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriac-corpus#44]
@jedwardwalters 
https://docs.google.com/a/tamu.edu/document/d/1nxnmU8h5uDiz5YGeCuI5VWba9Mx42PnAxq3Nn5A1ARo/edit?usp=sharing 
I just sent you a link with this message but it probably ought to be here in an issue:

"Ages ago I cut and pasted from the html of Kristian Heal's current online version of the Chronicle of Edessa. I added the section numbers to that transcription. It would be great if we could add those to the TEI using <ab> and the appropriate @n attribute. Note that they are not in order as these section numbers are in chronological order where the text itself is not. Perhaps we need to discuss this situation and figure out a way to give users the option of viewing a text as written and in this other way. Most of the English translations rearrange the text to put it into chronological order. Let me know if you want to discuss this at all. Thanks Jamey!"

After sending this, I checked the TEI. The pages are there as div elements with the page numbers as head elements. That makes sense but might make the re-ordering of the text difficult. I'll have a think about this. We should discuss.

**Comment by dlschwartz** [comment]
@jedwardwalters 
I need to look into things a bit further but we are thinking that perhaps we have made too great a use of the div element. Pagination, etc. should be handled with a pb element or perhaps a milestone element with a type attribute. We need to be able to accommodate multiple pagination systems and allow users to view according to those systems. Since XML does not allow overlapping elements, we need self-closing milestone elements. 

A good example of the need is here. The transcription we have from Kristian of the Chronicle of Edessa leaves a lot of information out: http://archive.org/stream/ChronicaMinoraI/GuidiChronicaMinoraI#page/n3/mode/1up. If we add the data in the margins of the edition, we would include the section number (in fact, this text has the sections of the text according to the order they appear in the text and according to the chronological ordering used in some editions: http://www.tertullian.org/fathers/chronicle_of_edessa.htm.) I need these section numbers in this text for SPEAR so we definitely want to add them. But, beyond that, this is data in the edition we are encoding that can be used to view in multiple arrangements of the text.

Let me look further at the encoding of the prose and poetry in the corpus and get back to you on what changes we need to make. I'll also think about what we might be able to do with a script as opposed to manually. Let me know if you want to talk through any of this.

Thanks Jamey.

**Comment by jedwardwalters** [comment]
Yes, I've actually been thinking about this as well. I initially looked at using the pb element, but I can't remember why I didn't incorporate it. I think maybe I was just going for keeping it uniform with a text like Aphrahat, which has sections instead of pages. But of course, uniformity isn't a virtue when there are better, more natural ways to do it! I'll try to brainstorm this a bit too, but do please let me know what thoughts/suggestions you have.

**Comment by dlschwartz** [comment]
Yeah, I think the important difference is between things related to the structure of a text and things related to a particular edition of the text. Pagination is edition specific, section breaks are about textual structure. The real problem I see, is that if we prioritize the section breaks in the encoding so that we can offer different text views, we still wouldn't want to leave out the page breaks (whether a pb element or a milestone element). But, if a user re-ordered text to view by the chronological order, then the page numbers would be out of order in a way that I fear would be confusing. For the Chron. Ed. we could follow Guidi's practice of only displaying the original order of the text as preserved but employing a double numbering system for the sections of the text, one of which indicates the order of the text as preserved, the other of which indicates the chronological order of the annals in the chronicle. This might take some more thought. At the level of principles for encoding the corpus, I think it is safe to say that we want to use p and div for structures in the text that have retain relevance regardless of edition, and use milestone type elements (pb and milestone) for edition-specific information. Let's both keep thinking and we can discuss this again soon.

**Comment by jedwardwalters** [comment]
Okay. I'm reading back through TEI guidelines right now to freshen my memory!

**Comment by jedwardwalters** [comment]
@dlschwartz @davidamichelson @wsalesky @nathangibson 
I updated the Chronicle of Edessa text structure as we discussed. You can view it here:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/57

One question I had (which will apply to other texts) is that now that I changed all the ed attributes to edRef in pb elements, I had to use an xml:id to declare the source in the sourceDesc, which mean to adjust the sourceDesc setup a little. But my question is this: I can't use the full URI as an xml:id, so i used an abbreviated form that it would accept: bibl659 (659 is the URI number for this work in syriaca.org/bibl). Is this okay? Should I do something else? 

You can view it here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/57.xml#L76

**Comment by dlschwartz** [comment]
@jedwardwalters, why the need for an xml:id in the edRef attribute? Wouldn't we prefer a bibl URI? TEI allows that, at least that's how I read the guidelines. Oxygen validates it as well. Am I missing something (he asks not having had a cup of coffee yet this morning!)?

**Comment by jedwardwalters** [comment]
@dlschwartz Ah, okay. I see that the actual edRef can take a URI. I was trying to set it up like they do in the examples where there is an xml:id attached to a source within the document, and then they use edRef to link to that source using the xml:id. So I was trying to "declare" an xml:id for the source and then use that for the edRef id.

But if we can bypass that step by just using the URIs for the edRef, then that's fine. I can make that change.

**Comment by dlschwartz** [comment]
TEI has a strong preference for xml:ids and tends to think of them as synonymous with URIs. This notion of a URI, however, is incompatible with W3C recommendations on URIs, the relative benefits of which are abundantly clear. I hope too much effort didn't go into the xml:ids.

**Comment by jedwardwalters** [comment]
Oh no, hardly any effort at all. I worked on it for a couple of minutes, made a decision and posted here for feedback. And it will only take a couple minutes on a quick find/replace to fix it.

**Comment by dlschwartz** [comment]
Excellent!

**Comment by jedwardwalters** [comment]
Closing this, since I think we solved our problem (for now anyway).
