### ISSUE TITLE
URI Assignment

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus#5]
@jedwardwalters This is to say go ahead and insert uris into each file in the publicationStmt as we discussed (see https://github.com/srophe/syriac-corpus/blob/master/data/tei/Aphrahat-Dem_1.xml#L51). Just start numerically with syriaccorpus.org/1 etc.

@wsalesky This should answer your query:
“I added some structure to the data repo, so that it can be easily deployed into eXist. However I noticed there are no ids. Our app relies heavily on the data in the idno elements. In fact it will not run without that data. Can we add fake (unique) ids for now and update them later? I can not really do any testing on the app without them.”

FYI for @nathangibson could you please provide us with NHSL work URIs for the demonstrations as a whole and for each demonstration and for the "Letter of an Inquirer" (see related issue https://github.com/srophe/syriac-corpus/issues/6 ).

@jedwardwalters After discussing this with @dlschwartz we have decided to scrap https://github.com/srophe/syriac-corpus/blob/master/data/tei/Aphrahat-Dem_1.xml#L73-L77  Instead, let's put the Syriaca.org work uri's as refs on the titles in the titleStmt: https://github.com/srophe/syriac-corpus/blob/master/data/tei/Aphrahat-Dem_1.xml#L6-L7

Please let me know if you have any questions.

**Comment by nathangibson** [comment]
OK, here you are: https://docs.google.com/spreadsheets/d/1d8gxz-Ax7bozQeAzy7ufzSjUn0z9muNHIi910A0gcuw/edit#gid=0

**Comment by jedwardwalters** [comment]
Thanks, everyone, for your comments here. Sorry for the delay--I was out of town for the last two weeks and didn't have much time for work. I'm back now and I'll start working on this stuff.

**Comment by davidamichelson** [comment]
@jedwardwalters I know the semester is just getting underway. Please let us know when you get these in as we can begin to see the texts in the test app.

**Comment by jedwardwalters** [comment]
That looks great, @nathangibson . Thank you!

@davidamichelson I'll get to work on this right away. Sorry for the delay!

**Comment by jedwardwalters** [comment]
@wsalesky I've added the URIs. Let me know if there's anything else you need me to do for this test phase to work.

**Comment by wsalesky** [comment]
Thank you! I will try to get a version of the app with data up tomorrow.

**Comment by wsalesky** [comment]
Initial version of the site: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/index.html
Use the browse and search to access current data. (Keyword, the others are hold overs from Syriaca.org that will need to be changed)

We can discuss search/browse and display options on the app branch:
https://github.com/srophe/syriac-corpus-app

Thanks!
