### ISSUE TITLE
XML file for the "letter" at the beginning of the Demonstrations

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriac-corpus#6]
@jedwardwalters I think we want a separated xml file for the letter that comes before the first demonstration. You would have to decide what to call this portion of the Demonstrations at line 6 of the header. In the body, it would be labeled as div1 type="part" n="0".

**Comment by dlschwartz** [comment]
See #5 for how to add a URI to this record.

**Comment by jedwardwalters** [comment]
Done.
