### ISSUE TITLE
Critical Apparatus

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#82]
@davidamichelson @davidamichelson @nathangibson 
Okay, I've been avoiding this question for a little while by just working on texts for which this issue is not applicable, but at some point we need to decide how to handle corpus texts that include variants in a critical apparatus.

There are two immediate questions:
1) Do we want to include these in our quick and dirty version?
2) And if so, which TEI critical edition style do we want to use (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TC.html#TCAPLK)?

**Comment by davidamichelson** [comment]
We do plan to include this using Hugh Cayless system and we should have at
least one text text with it. We need to ask Hugh what style, can you email
him?
