### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#87]
Some of the texts appear to be spilling out of the center text container. See: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/1

**Comment by wsalesky** [comment]
Browser and OS?

**Comment by jedwardwalters** [comment]
Yes, both. Is it not happening for you? I'll take a screen shot.

**Comment by jedwardwalters** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/11543800/26123593/72ad72ce-3a49-11e7-8c1e-b6d073f83f72.jpeg)

**Comment by wsalesky** [comment]
Sorry, I meant which browser and which operating system. I did notice this in Safari, not Chrome or Firefox on my Mac.

**Comment by jedwardwalters** [comment]
Ah! Of course. Sorry.

Using Safari, and my OS is 10.12.4 (Sierra).

**Comment by wsalesky** [comment]
Okay, thanks!

**Comment by wsalesky** [comment]
@jedwardwalters This seems to be resolved on my mac, how does it look to you? If it is fine, you can close this issue.

**Comment by jedwardwalters** [comment]
Yep, looks good on mine too.
