### ISSUE TITLE
Adjustments to TEI structure?

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#92]
@wsalesky @dlschwartz @davidamichelson @nathangibson 

Dan and Dave, 
Nathan and I met with Joel Kalvesmaki and discussed Syriaca/Text Align Network stuff. After the conference, he gave a few comments on one of our documents and shared it as a pull request (not expecting us to merge it, just as a way of sharing it).

You can view it here: https://github.com/srophe/syriac-corpus/pull/91/commits/9bed1b8777e86d96179d12945a1c1ed85d92f6a4

So, I wanted to see if anyone thinks we should incorporate some of his changes while we are still relatively early in the schema development stage. Thoughts?

**Comment by nathangibson** [comment]
My 2 cents: 
1. Not sure what happened in the [publicationStmt](https://github.com/srophe/syriac-corpus/blob/master/data/tei/1.xml#L56), but it seems we should do something to make that valid TEI. Perhaps orgName directly inside distributor?
2. At [availability](https://github.com/srophe/syriac-corpus/blob/master/data/tei/1.xml#L65), do we need to specify the rights holder as Joel has suggested, or does authority effectively do that? Underlying text is public domain, but "All .xml and .html data copyright Brigham Young University and licensed under the Creative Commons Attribution 4.0 International Public License" according to the footer.
3. Joel says TEI community consensus is to do away with div1, div2, etc. Also that we don't need a div1 directly inside body containing the entire text. I don't remember the decisions that went into this but it would be valid TEI to eliminate div1 and change div2 to just div. 
4. If we continue using English metadata and heads, as I assume we will, then I think it makes sense to continue labeling the individual Syriac heads and ps with xml:lang="syr". But I don't see that we have declared xml:lang="en" anywhere higher up in the tree. Should we do this on the root TEI element?

**Comment by davidamichelson** [comment]
Let's discuss in an editorial meeting. These look interesting. To avoid
breaking the XSLT please don't merge this branch however.

**Comment by jedwardwalters** [comment]
@nathangibson @davidamichelson @dlschwartz 

I re-structured Demonstration 1 as an example/test. See pull request #97.

Or just view the revised file here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/1.xml

Any thoughts/comments?

**Comment by jedwardwalters** [comment]
@wsalesky 
FYI: We have decided to ditch the numbered divs in the Corpus after all. You can see the above example that I re-structured. Any thoughts/comments on your end about this new structure?

**Comment by nathangibson** [comment]
@jedwardwalters I don't see any issues.

**Comment by wsalesky** [comment]
@jedwardwalters Seems fine to me. If you find anything that is no longer rendering correctly please create a bug and we will fix as we find them.

**Comment by jedwardwalters** [comment]
Okay. Will do.
