### ISSUE TITLE
Sample file to be removed?

### ISSUE THREAD

**Issue by nathangibson** [srophe/syriac-corpus#94]
@jedwardwalters 
Randomly came across this file http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/9999993 which seems to be a sample? Has title "Mark (Peshitta Version)" but text of Demonstration 1. Plus a seemingly fake URI.

**Comment by dlschwartz** [comment]
I think it is safe to remove this. If you think we might need it in the future (which sounds unlikely) you could keep it on your hard drive. Probably not necessary.

**Comment by jedwardwalters** [comment]
Done.
